
pipeline {
    agent any

    environment {
        IMAGE_NAME = 'jenk-workshop-rate'
        VERSION = "v${env.BUILD_NUMBER}"
        REPO = 'shayc12'
        CREDENTIALS_ID = 'docker-credentials'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh '''
                    docker build --target build --tag ${IMAGE_NAME}:${VERSION}-build -f welcome/app/bookinfo/src/productpage/Dockerfile welcome/app/bookinfo/src/productpage/
                    '''
                }
                }

            }

        stage('Lint/Test') {
            steps {
                script {
                    sh 'docker build --target lint-test --tag ${IMAGE_NAME}:${VERSION}-lint-test -f welcome/app/bookinfo/src/productpage/Dockerfile welcome/app/bookinfo/src/productpage/'
                    sh 'docker run --rm ${IMAGE_NAME}:${VERSION}-lint-test'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    
                    sh '''
                    docker build --target test --tag ${IMAGE_NAME}:${VERSION}-test -f welcome/app/bookinfo/src/productpage/Dockerfile welcome/app/bookinfo/src/productpage/
                    docker run --rm ${IMAGE_NAME}:${VERSION}-test
                    '''
                }
            }
        }
        

        stage('Run') {
            steps {
                script {

                    sh '''
                    docker build --target run --tag ${REPO}/${IMAGE_NAME}:${VERSION} -f welcome/app/bookinfo/src/productpage/Dockerfile welcome/app/bookinfo/src/productpage/
                    '''
                
            }
        }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry("https://index.docker.io/v1/", "${CREDENTIALS_ID}") {
                        sh '''
                        docker tag ${REPO}/${IMAGE_NAME}:${VERSION} ${REPO}/${IMAGE_NAME}:latest
                        docker push ${REPO}/${IMAGE_NAME}:latest
                        '''
                    }
                }
            }
        }
    }
}